version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 575108960382.dkr.ecr.us-east-1.amazonaws.com/python-app
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t 575108960382.dkr.ecr.us-east-1.amazonaws.com/python-app:$IMAGE_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 575108960382.dkr.ecr.us-east-1.amazonaws.com/python-app:$IMAGE_TAG
      - printf '{"ImageURI":"%s"}' 575108960382.dkr.ecr.us-east-1.amazonaws.com/python-app:$IMAGE_TAG > imageDetail.json

artifacts:
  files:
    - imageDetail.json
